### ISSUE TITLE
Errors: 'Could not establish connection' and 'Extension context invalidated'

### ISSUE THREAD

**Issue by max-ostapenko** [HTTPArchive/wappalyzer#66]
**Platform**
Which platform does the bug apply to?

- WebExtension (Google Chrome)

**Describe the bug**
While using the local extension version to test the new rules I often have the errors:
- `Uncaught (in promise) Error: Extension context invalidated.`
- `Error: Could not establish connection. Receiving end does not exist.`

I'm not sure if due to these errors there are issues with the technologies being detected and displayed.

**To Reproduce**
Approximate steps:
1 Go to a tested website 1
2. Update the rules
3. Hit Refresh in chrome://extensions/
4. Go to a tested website 2 and refresh the page
5. Check the errors 

**Expected behavior**
 - handle these cases in extension communication, or make errors of tech detection more obvious

**Comment by tunetheweb** [comment]
We don't own this extension. Wappalyzer does. This is just a clone of their repo as off when they went closed-source. As they are closed-source now I don't think you can contribute any fixes.
