### ISSUE TITLE
Osano detection issues

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/wappalyzer#75]
[Osano](https://github.com/HTTPArchive/wappalyzer/blob/main/src/technologies/o.json#L1770) (cookie compliance) used to have ~100k origins in the Tech Report, but now there's <10k. Seems like the detection may need to be updated.

![Image](https://github.com/user-attachments/assets/5585c7f4-df8c-41df-8c31-0f923b9e526e)

**Comment by max-ostapenko** [comment]
The current adoption is expected.
Osano rules were fixed back then: https://github.com/HTTPArchive/wappalyzer/commit/d98814d4956c87e3ca9c953d41c93f40216e9111

**Comment by max-ostapenko** [comment]
Actually not expected at all.
The missing rule relates to the Osano's open-source banner.

So it makes sense to add it back, with a note that it's OSS version.

Unfortunately we can't check the reason for the deletion.
